// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwcwvlrjyqgoqpywwfud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3Y3d2bHJqeXFnb3FweXd3ZnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzgzMjQsImV4cCI6MjA2MzU1NDMyNH0.3wcwKkSZqeuJVpN2jxKYZ_xrqPBL8ABiJfP4XbFk4_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);